// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVVEZ3s3g3nVH3XHctJCYyxnR1sVMiWXg',
    appId: '1:625428081040:web:be137edb22ff93b3cdab15',
    messagingSenderId: '625428081040',
    projectId: 'cine-booking-team6',
    authDomain: 'cine-booking-team6.firebaseapp.com',
    storageBucket: 'cine-booking-team6.firebasestorage.app',
    measurementId: 'G-X2X1RTFNXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhEfoiTIdkhtYjbUBhIri_L1pGeeRnuk4',
    appId: '1:625428081040:android:a993677406bd394dcdab15',
    messagingSenderId: '625428081040',
    projectId: 'cine-booking-team6',
    storageBucket: 'cine-booking-team6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3AEH2x_Qc0bdyDSvdEXsmCSVVfbpJFkE',
    appId: '1:625428081040:ios:0f979240009f8b27cdab15',
    messagingSenderId: '625428081040',
    projectId: 'cine-booking-team6',
    storageBucket: 'cine-booking-team6.firebasestorage.app',
    iosBundleId: 'com.example.cineBookingTeam6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3AEH2x_Qc0bdyDSvdEXsmCSVVfbpJFkE',
    appId: '1:625428081040:ios:0f979240009f8b27cdab15',
    messagingSenderId: '625428081040',
    projectId: 'cine-booking-team6',
    storageBucket: 'cine-booking-team6.firebasestorage.app',
    iosBundleId: 'com.example.cineBookingTeam6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVVEZ3s3g3nVH3XHctJCYyxnR1sVMiWXg',
    appId: '1:625428081040:web:2c3eb1bdf7926323cdab15',
    messagingSenderId: '625428081040',
    projectId: 'cine-booking-team6',
    authDomain: 'cine-booking-team6.firebaseapp.com',
    storageBucket: 'cine-booking-team6.firebasestorage.app',
    measurementId: 'G-06GYD7LN94',
  );
}
